GET http://localhost:3000/users

###
GET http://localhost:3000/users/1

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Johny",
    "email": "johny@gmail.com",
    "gender": "Male"
}

###
PATCH http://localhost:3000/users/1
Content-Type: application/json

{
    "name": "Johny Doe",
    "email": "johny@gmail.com",
    "gender": "Male"
}

###
DELETE http://localhost:3000/users/2
